name = "sensor-plc-backend"
main = "server/main.py"
compatibility_date = "2024-12-30"
compatibility_flags = [ "python_workers" ]

[[d1_databases]]
binding = "DB"
database_name = "sensor_plc_db"
database_id = "dfdf9c26-2ef5-4c8c-adcd-01fdde59b365" # 유저가 D1 생성 후 이 부분을 채워야 합니다.

[observability]
enabled = true
