name = "sensor-plc-backend"
main = "server/main.py"
compatibility_date = "2024-12-30"
compatibility_flags = [ "python_workers" ]

[vars]
SUPABASE_URL = "https://wjqtxvtlqswwxqdciuwm.supabase.co"

[observability]
enabled = true
